[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[context.production]
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200